### ISSUE TITLE
xyz(longitude, latitude, feature) data in a csv file to tiff using geotrellis

### ISSUE THREAD

**Issue by ksaliya** [locationtech/geotrellis#2896]
How do I convert longitude, latitude and attribute data in a csv file to a tiff file using geotrellis?
I have read the csv data into a spark data frame and transformed the data to an rdd containing points with features.  I'm not sure where to go from here. Can anyone guide me in the right direction with an example. Here's what I have done so far.

```scala
abstract class Feature[D] {
  type G <: Geometry
  val geom: G
  val data: D
}

case class PointFeature[D](geom: Point, data: D) extends Feature[D] {
  type G = Point
}

val df = spark.read.csv("path/to/file.csv")
// +-------+-------+--------+
// |   x   |   y   | Feature|
// |-------+-------+--------|
// | 10110 | 23450 |  0.1   |
// | 10111 | 23450 |  0.2   |
// | 10112 | 23450 |  0.7   |
// +-------+-------+--------+
 
 val points_with_features = df.rdd.map(x => PointFeature(Point(x(0).asInstanceOf[Double], x(1).asInstanceOf[Double]), x(2).asInstanceOf[Double]))
```

**Comment by pomadchin** [comment]
The `PointFeature` [definition is the following](https://github.com/locationtech/geotrellis/blob/f8af6e6d72749b8fb175a0c44cbc7d027a940686/vector/src/main/scala/geotrellis/vector/Feature.scala#L49): 

```scala
object PointFeature {
  def apply[D](geom: Point, data: D): Feature[Point, D] =
    Feature(geom, data)

  def unapply[D](feature: Feature[Point, D]) =
    Some(feature.geom -> feature.data)
}
```

Vector to Raster operation called rasterization: 

https://github.com/locationtech/geotrellis/blob/f8af6e6d72749b8fb175a0c44cbc7d027a940686/spark/src/main/scala/geotrellis/spark/rasterize/Implicits.scala

So what you need to do: 

```scala
import geotrellis.spark._
import geotrellis.spark.tiling._
import geotrellis.vector._
import geotrellis.raster._
      
val df = spark.read.csv("path/to/file.csv")
// +-------+-------+--------+
// |   x   |   y   | Feature|
// |-------+-------+--------|
// | 10110 | 23450 |  0.1   |
// | 10111 | 23450 |  0.2   |
// | 10112 | 23450 |  0.7   |
// +-------+-------+--------+

val featuresRDD: RDD[Feature[Point, Double]] = 
  df
    .rdd
    .map(row => PointFeature(Point(row.getAs[Double](0), row.getAs[Double](1)), row.getAs[Double](2)))
      
val cellType: CellType = DoubleCellType // some cellType
val extent: Extent = ??? // some extent
val tileLayout: TileLayout = ??? // some tileLayout
val layoutDefinition: LayoutDefinition = LayoutDefinition(extent, tileLayout)

val rastersRDD = featuresRDD.rasterize(cellType, layoutDefinition)
```

**Comment by ksaliya** [comment]
I have defined `extent`, `tileLayout` and `layoutDefinition`. However, the method `rasterize` on `featureRDD` is not recognized. `featureRDD` is of type `RDD[PointFeature[Double]]` and the error says that `rasterize` is not a member.

**Comment by pomadchin** [comment]
Hey @kevinzau , double check your imports. Probably ambiguous impilcits resolution happens or smth like that. Check out this compiling snippet: https://scastie.scala-lang.org/7GDgoyEyTN6nhamZtql0BA

**Comment by kevinzau** [comment]
@pomadchin You probably meant to send that to @ksaliya :)

**Comment by pomadchin** [comment]
@kevinzau sorry for that! It's a gitter auto substitution ): 

Closing this issue as it was resolved. The example I posted didn't work due to custom `Feature` classes defined in the scope.

**Comment by ksaliya** [comment]
@pomadchin Thank you for your help. Although, I did make some progress with your example, I'm still not sure how to generate a tiff file properly.
